import React, { useState } from 'react';


function TechStackSection({ title, items }) {
  const [isTechStackVisible, setTechStackVisible] = useState(false);

  const toggleTechStack = () => {
    setTechStackVisible(!isTechStackVisible);
  };

  return (
    <div>
      <h2>{title}</h2>
      <button className="dropdown-toggle" onClick={toggleTechStack}>
        {isTechStackVisible ? 'Hide Tech Stack' : 'Show Tech Stack'}
      </button>
      {isTechStackVisible && (
        <div className="dropdown-content">
          <ul className="index-list">
            {items.map((item, index) => (
              <li key={index}>{item}</li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}

function About() {
  const languages = ['HTML', 'CSS', 'SASS', 'PHP', 'React.js', 'JavaScript', 'Liquid'];
  const developmentTools = ['MySQL', 'FTP', 'NPM', 'Rest API', 'WordPress', 'Shopify', 'Headless CMS'];
  const designTools = ['Figma', 'XD', 'Procreate', 'Photoshop', 'Illustrator'];

  return (
    <>
      <div className="about-section">
        <h1>About</h1>
        <h3>I like to dabble.</h3>
        <h2>Astronomy Nerd. Video Game Lover. Amateur Digital Artist. Iced Matcha Latte Enthusiast. INFP.</h2>
        <h2>As a developer skilled in both technical expertise and creative abilities, I am on a mission to design user-friendly websites that are both distinctive and intuitive for all users.</h2>
        <p>Image generated by NASA's APOD API.</p>
      </div>
      <div className="tech-stack-section">
        <h1>What I'm Well-Versed In</h1>
        <TechStackSection title="Languages" items={languages} />
        <TechStackSection title="Development Tools" items={developmentTools} />
        <TechStackSection title="Design Tools" items={designTools} />
      </div>
    </>
  );
}

export default About;
